"""
Data layer: loads the support tickets CSV into an in-memory-backed
SQLite database so it can be queried with SQL (generated by the LLM
from natural language, or used directly by the anomaly detector).

SQLite (rather than plain pandas filtering) was chosen because:
  - It gives the LLM a well-understood target language (SQL) to
    generate, instead of inventing a custom DSL.
  - It's zero-install, zero-cost, and ships with Python's stdlib.
  - It scales the same approach to much larger CSVs without a
    redesign (swap the SQLite URL for Postgres later, code unchanged).
"""

import sqlite3
from pathlib import Path
from contextlib import contextmanager

import pandas as pd

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
CSV_PATH = DATA_DIR / "support_tickets.csv"
DB_PATH = DATA_DIR / "tickets.db"

TABLE_NAME = "tickets"

# Schema description handed to the LLM as grounding context for NL -> SQL.
SCHEMA_DESCRIPTION = f"""
Table name: {TABLE_NAME}

Columns:
  ticket_id            TEXT    - unique ticket identifier, e.g. 'TKT-001'
  created_at           TEXT    - ticket creation timestamp, format 'YYYY-MM-DD HH:MM'
  category             TEXT    - one of: 'Billing', 'Technical', 'General'
  priority             TEXT    - one of: 'Low', 'Medium', 'High', 'Critical'
  status               TEXT    - one of: 'Open', 'Resolved', 'Escalated'
  response_time_hrs    REAL    - hours from creation to first agent response
  resolution_time_hrs  REAL    - hours from creation to resolution; NULL if unresolved
  agent_id             TEXT    - support agent identifier, e.g. 'AGT-04'
  customer_rating      REAL    - satisfaction rating 1-5; NULL if unresolved
  issue_summary        TEXT    - free-text description of the issue
""".strip()


def load_csv_to_sqlite(force_reload: bool = False) -> None:
    """Load the CSV into SQLite. Safe to call repeatedly (idempotent)."""
    if DB_PATH.exists() and not force_reload:
        return

    if not CSV_PATH.exists():
        raise FileNotFoundError(
            f"Expected dataset at {CSV_PATH}. Place support_tickets.csv there."
        )

    df = pd.read_csv(CSV_PATH)
    conn = sqlite3.connect(DB_PATH)
    try:
        df.to_sql(TABLE_NAME, conn, if_exists="replace", index=False)
        conn.commit()
    finally:
        conn.close()


@contextmanager
def get_connection():
    """Context-managed SQLite connection with row access by column name."""
    load_csv_to_sqlite()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
    finally:
        conn.close()


def run_readonly_query(sql: str) -> list[dict]:
    """
    Execute a SELECT-only query and return rows as a list of dicts.
    Raises ValueError if the query looks like anything other than a
    read (defense in depth alongside the LLM-layer validation).
    """
    forbidden = (
        "insert", "update", "delete", "drop", "alter",
        "attach", "detach", "pragma", "create", "replace into",
    )
    lowered = sql.strip().lower()
    if not lowered.startswith("select"):
        raise ValueError("Only SELECT queries are permitted.")
    if any(word in lowered for word in forbidden):
        raise ValueError("Query contains a disallowed keyword.")

    with get_connection() as conn:
        cursor = conn.execute(sql)
        columns = [d[0] for d in cursor.description]
        rows = [dict(zip(columns, row)) for row in cursor.fetchall()]
    return rows


def get_dataframe() -> pd.DataFrame:
    """Load the full dataset as a DataFrame (used by the anomaly detector)."""
    load_csv_to_sqlite()
    with get_connection() as conn:
        df = pd.read_sql(f"SELECT * FROM {TABLE_NAME}", conn)
    return df
